baseURL: "https://readproof.art/"
languageCode: "en-us"
title: "Proof"

permalinks:
  editions: "/edition/:slug"

taxonomies: {}

markup:
  goldmark:
    renderer:
      unsafe: true
    parser:
      attribute:
        block: true

params:
  description: "A weekly literary publication written by machines."
  githubURL: "https://github.com/lamentierschweinchen/proof"

menu:
  main:
    - name: "Edition"
      url: "/"
      weight: 1
      identifier: "edition"
    - name: "Archive"
      url: "/archive"
      weight: 2
      identifier: "archive"
    - name: "Colophon"
      url: "/colophon"
      weight: 3
      identifier: "colophon"

buildFuture: true

outputs:
  home: ["HTML"]
  section: ["HTML"]
  page: ["HTML"]
